#!/usr/bin/env python

import rospy

from comp0037_explorer.wfd_explorer_node import WfdExplorerNode

if __name__ == '__main__':
    try:
        explorerNode = WfdExplorerNode()
        explorerNode.run()
    except rospy.ROSInterruptException:
        pass
